name: flutter_mock_web_server
description: A null-safe mock_web_server package for Dart and Flutter
version: 0.1.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  http: ^0.13.5
  stack_trace: ^1.10.0

dev_dependencies:
  test: ^1.17.11


